name: Devcontainer Build

on:
  push:
    branches: [main]
  pull_request:
    paths: ['.devcontainer/**']

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: false
